### ISSUE TITLE
ask 

### ISSUE THREAD

**Issue by ari123mster** [ThetPaing/freeradius-laravel#1]
hello sir
I'd like to ask
So that's the Freeradius and Laravel database in one?
Or are there two databases, Laravel and Freeradius?

**Comment by ThetPaing** [comment]
Hello,
Yes, it's one database that combines both FreeRADIUS and Laravel.

**Comment by ari123mster** [comment]
thanks for your information sir

Pada Kam, 13 Jun 2024 10.18, Thet Paing Oo ***@***.***>
menulis:
